#!/bin/bash
. /usr/bin/aops-vulcanus

MANAGER_CONSTANT="ragdoll"
MANAGER_CONFIG_FILE=/etc/ragdoll/gala-ragdoll.conf

function main() {
  if [ "${OPERATION}" = "start" ]; then
    create_config_file "${MANAGER_CONFIG_FILE}" "ragdoll"
  fi
  start_or_stop_service "${MANAGER_CONSTANT}"
  exit $?
}

main
