---
- name: install gala-filetrace and dependency
  dnf:
    name: gala-filetrace libcurl libelf libbpf zlib nlohmann-json cpp-httplib kernel-devel-$(uname -r)
    state: present
  when: action == "start" or action == "update"
- name: enable gala-filetrace systemd
  command: systemctl enable gala-filetrace
  when: action == "start" or action == "update"
- name: stop gala-filetrace when action is update
  command: systemctl stop gala-filetrace
  when: action == "update" or action == "stop"
- name: start gala-filetrace systemd
  command: systemctl start gala-filetrace
  when: action == "update" or action == "start"
